---
title: "Use Case: Importing Timestamps"
author: "Hauke Sonnenberg"
date: "`r Sys.Date()`"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Use Case: Importing Timestamps}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r setup, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

Assume you have to read timestamps from a text file that is recorded by a
measuring device. The device is first configured not to switch between summer
time and standard time. At some day it is reconfigured so that it does the 
switch between summer time and standard time and vice versa. How can we read 
these timestamps into R?

```{r}
kwb.datetime::date_range_CEST(2019)

times_local <- seq(
  as.POSIXct("2019-03-15", tz = "Europe/Berlin"),
  as.POSIXct("2019-11-01", tz = "Europe/Berlin"),
  by = 1800
)

timestamps_local <- as.character(times_local)

timestamps_local[grepl("^2019-10-27 02", timestamps_local)]

times_local_new <- kwb.datetime::berlin_local_timestamps_to_POSIXct(timestamps_local)

stopifnot(all(times_local == times_local_new))
```

```{r}
times_standard <- seq(
  as.POSIXct("2019-03-15", tz = "Etc/GMT-1"),
  as.POSIXct("2019-11-01", tz = "Etc/GMT-1"),
  by = 1800
)

timestamps_standard <- as.character(times_standard)

timestamps_standard[grepl("^2019-10-27 02", timestamps_standard)]

times_standard_new <- as.POSIXct(timestamps_standard, tz = "Etc/GMT-1")

stopifnot(all(times_standard == times_standard_new))

attributes(times_standard_new)
```

