#
# This test file has been generated by kwb.test::create_test_files()
#

test_that("berlinNormalTimeToUTC() works", {

  expect_error(
    kwb.datetime:::berlinNormalTimeToUTC(x = 1)
    # is.character(x) is not TRUE
  )
   expect_error(
    kwb.datetime:::berlinNormalTimeToUTC(x = "a")
    # character string is not in a standard unambiguous format
  )

})

