#
# This test file has been generated by kwb.test::create_test_files()
#

test_that("toUTC() works", {

  expect_error(
    kwb.datetime:::toUTC(x = NULL)
    # inherits(x, "POSIXt") is not TRUE
  )

})

