#
# This test file has been generated by kwb.test::create_test_files()
#

test_that("daysPerMonth() works", {

  kwb.datetime:::daysPerMonth(date = character())
   kwb.datetime:::daysPerMonth(date = logical())
   expect_error(
    kwb.datetime:::daysPerMonth(date = NULL)
    # do not know how to convert 'date' to class “POSIXlt”
  )
   expect_error(
    kwb.datetime:::daysPerMonth(date = numeric())
    # 'origin' must be supplied
  )
   expect_error(
    kwb.datetime:::daysPerMonth(date = 'a')
    # character string is not in a standard unambiguous format
  )

})

