#
# This test file has been generated by kwb.test::create_test_files()
#

test_that("timestampIn() works", {

  kwb.datetime:::timestampIn(tstamps = 1)
   kwb.datetime:::timestampIn(tstamps = 1:2)
   kwb.datetime:::timestampIn(tstamps = "a")
   kwb.datetime:::timestampIn(tstamps = c("a", "b"))
   kwb.datetime:::timestampIn(tstamps = TRUE)
   kwb.datetime:::timestampIn(tstamps = FALSE)
   kwb.datetime:::timestampIn(tstamps = as.POSIXct("2018-06-03 23:50:00"))
   kwb.datetime:::timestampIn(tstamps = list(key = c("a", "b"), value = 1:2))

})

