#
# This test file has been generated by kwb.test::create_test_files()
#

test_that("utcToLocalTime() works", {

  expect_error(
    kwb.datetime:::utcToLocalTime(x = 1, tz = 1)
    # is.character(x) is not TRUE
  )
   expect_error(
    kwb.datetime:::utcToLocalTime(x = "a", tz = 1)
    # character string is not in a standard unambiguous format
  )

})

