#
# This test file has been generated by kwb.test::create_test_files()
#

test_that("localNormalTimeToLocalTime() works", {

  expect_error(
    kwb.datetime:::localNormalTimeToLocalTime(x = 1, UTCOffset = 1)
    # is.character(x) is not TRUE
  )
   expect_error(
    kwb.datetime:::localNormalTimeToLocalTime(x = "a", UTCOffset = 1)
    # character string is not in a standard unambiguous format
  )

})

