#
# This test file has been generated by kwb.test::create_test_files()
#

test_that("hsQuaStr() works", {

  expect_error(
    kwb.datetime:::hsQuaStr(tstamp = NULL)
    # invalid format '%d'; use format %f, %e, %g or %a for numeric objects
  )
   expect_error(
    kwb.datetime:::hsQuaStr(tstamp = numeric())
    # invalid 'trim' argument
  )

})

