#
# This test file has been generated by kwb.test::create_test_files()
#

test_that("timeFormatToRegex() works", {

  kwb.datetime:::timeFormatToRegex(timeformat = NULL)
   kwb.datetime:::timeFormatToRegex(timeformat = numeric())
   kwb.datetime:::timeFormatToRegex(timeformat = 1)
   kwb.datetime:::timeFormatToRegex(timeformat = 1:2)
   kwb.datetime:::timeFormatToRegex(timeformat = character())
   kwb.datetime:::timeFormatToRegex(timeformat = 'a')
   kwb.datetime:::timeFormatToRegex(timeformat = c('a', 'b'))
   kwb.datetime:::timeFormatToRegex(timeformat = logical())
   kwb.datetime:::timeFormatToRegex(timeformat = TRUE)
   kwb.datetime:::timeFormatToRegex(timeformat = FALSE)

})

