#
# This test file has been generated by kwb.test::create_test_files()
#

test_that("hsTsIn() works", {

  expect_error(
    kwb.datetime:::hsTsIn(... = NULL)
    # unused argument (... = NULL)
  )
   expect_error(
    kwb.datetime:::hsTsIn(... = numeric())
    # unused argument (... = numeric(0))
  )
   expect_error(
    kwb.datetime:::hsTsIn(... = 1)
    # unused argument (... = 1)
  )
   expect_error(
    kwb.datetime:::hsTsIn(... = 1:2)
    # unused argument (... = 1:2)
  )
   expect_error(
    kwb.datetime:::hsTsIn(... = character())
    # unused argument (... = character(0))
  )
   expect_error(
    kwb.datetime:::hsTsIn(... = 'a')
    # unused argument (... = "a")
  )
   expect_error(
    kwb.datetime:::hsTsIn(... = c('a', 'b'))
    # unused argument (... = c("a", "b"))
  )
   expect_error(
    kwb.datetime:::hsTsIn(... = logical())
    # unused argument (... = logical(0))
  )
   expect_error(
    kwb.datetime:::hsTsIn(... = TRUE)
    # unused argument (... = TRUE)
  )
   expect_error(
    kwb.datetime:::hsTsIn(... = FALSE)
    # unused argument (... = FALSE)
  )

})

