#
# This test file has been generated by kwb.test::create_test_files()
#

test_that("sequenceOfTimestamps() works", {

  expect_error(
    kwb.datetime:::sequenceOfTimestamps(from = 1, to = 1)
    # is.character(from) && is.character(to) is not TRUE
  )
   expect_error(
    kwb.datetime:::sequenceOfTimestamps(from = "a", to = "a")
    # character string is not in a standard unambiguous format
  )

})

