#
# This test file has been generated by kwb.test::create_test_files()
#

test_that("toTimezone() works", {

  expect_error(
    kwb.datetime:::toTimezone(x = NULL, tz = NULL)
    # inherits(x, "POSIXt") is not TRUE
  )

})

