#
# This test file has been generated by kwb.test::create_test_files()
#

test_that("hsQuaStr() works", {

  kwb.datetime:::hsQuaStr(tstamp = as.POSIXct("2018-06-03 23:50:00"))
   expect_error(
    kwb.datetime:::hsQuaStr(tstamp = 1)
    # invalid 'trim' argument
  )

})

