#
# This test file has been generated by kwb.test::createTestFiles()
#

test_that("hsTsBefore() works", {

  expect_error(kwb.datetime:::hsTsBefore())
})

test_that("hsTsAfter() works", {

  expect_error(kwb.datetime:::hsTsAfter())
})

test_that("hsTsIn() works", {

  expect_error(hsTsIn())
})

test_that("timestampIn() works", {

  expect_error(timestampIn())
})

