#
# This test file has been generated by kwb.test::create_test_files()
#

test_that("toGmtRelativePosix() works", {

  kwb.datetime:::toGmtRelativePosix(timestamp = character())
   kwb.datetime:::toGmtRelativePosix(timestamp = 'a')
   kwb.datetime:::toGmtRelativePosix(timestamp = c('a', 'b'))
   expect_error(
    kwb.datetime:::toGmtRelativePosix(timestamp = NULL)
    # is.character(timestamp) is not TRUE
  )

})

