#
# This test file has been generated by kwb.test::createTestFiles()
#

test_that("date_range_CEST() works", {

  expect_error(date_range_CEST())
})

test_that("currentDateString() works", {

  currentDateString()
})

test_that("currentQuarter() works", {

  currentQuarter()
})

test_that("currentYear() works", {

  currentYear()
})

test_that("matchingTimeFormat() works", {

  expect_error(matchingTimeFormat())
})

test_that("hasTimeFormat() works", {

  expect_error(hasTimeFormat())
})

test_that("timeFormatToRegex() works", {

  expect_error(kwb.datetime:::timeFormatToRegex())
})

test_that("reformatTimestamp() works", {

  expect_error(reformatTimestamp())
})

test_that("daylightSavingTimeInEffect() works", {

  expect_error(kwb.datetime:::daylightSavingTimeInEffect())
})

test_that("hsTsInfo() works", {

  expect_error(kwb.datetime:::hsTsInfo())
})

test_that("hsQua() works", {

  expect_error(kwb.datetime:::hsQua())
})

test_that("hsQuaStr() works", {

  expect_error(kwb.datetime:::hsQuaStr())
})

test_that("intervalKey() works", {

  expect_error(intervalKey())
})

test_that(".timestamp_type_info() works", {

  kwb.datetime:::.timestamp_type_info()
})

test_that(".intervalKeyFormat() works", {

  expect_error(kwb.datetime:::.intervalKeyFormat())
})

test_that("resetTimePart() works", {

  expect_error(resetTimePart())
})

test_that("hsDateStr() works", {

  expect_error(hsDateStr())
})

test_that("hsTStampsPerDay() works", {

  expect_error(kwb.datetime:::hsTStampsPerDay())
})

test_that("daysPerMonth() works", {

  expect_error(daysPerMonth())
})

