#
# This test file has been generated by kwb.test::create_test_files()
#

test_that("utcOffset() works", {

  expect_error(
    kwb.datetime:::utcOffset(LocalDateTime = 1, DateTimeUTC = 1)
    # is.character(LocalDateTime) && is.character(DateTimeUTC) is not TRUE
  )
   expect_error(
    kwb.datetime:::utcOffset(LocalDateTime = "a", DateTimeUTC = "a")
    # character string is not in a standard unambiguous format
  )

})

