#
# This test file has been generated by kwb.test::create_test_files()
#

test_that("hsTStampsPerDay() works", {

  expect_error(
    kwb.datetime:::hsTStampsPerDay(tstamps = NULL)
    # no rows to aggregate
  )
   expect_error(
    kwb.datetime:::hsTStampsPerDay(tstamps = numeric())
    # invalid 'trim' argument
  )

})

