#
# This test file has been generated by kwb.test::create_test_files()
#

test_that("hsToPosix() works", {

  kwb.datetime:::hsToPosix(datetime = character(), ... = NULL)
   kwb.datetime:::hsToPosix(datetime = character(), ... = numeric())
   kwb.datetime:::hsToPosix(datetime = character(), ... = 1)
   kwb.datetime:::hsToPosix(datetime = character(), ... = 1:2)
   kwb.datetime:::hsToPosix(datetime = character(), ... = character())
   kwb.datetime:::hsToPosix(datetime = character(), ... = 'a')
   kwb.datetime:::hsToPosix(datetime = character(), ... = c('a', 'b'))
   kwb.datetime:::hsToPosix(datetime = character(), ... = logical())
   kwb.datetime:::hsToPosix(datetime = character(), ... = TRUE)
   kwb.datetime:::hsToPosix(datetime = character(), ... = FALSE)
   expect_error(
    kwb.datetime:::hsToPosix(datetime = NULL, ... = NULL)
    # datetime is not of one of the supported classes 'character', 'Date', 'POSIXt'
  )
   expect_error(
    kwb.datetime:::hsToPosix(datetime = 'a', ... = NULL)
    # character string is not in a standard unambiguous format
  )

})

