#
# This test file has been generated by kwb.test::create_test_files()
#

test_that(".intervalKeyFormat() works", {

  expect_error(
    kwb.datetime:::.intervalKeyFormat(itype = NULL)
    # argument is of length zero
  )
   expect_error(
    kwb.datetime:::.intervalKeyFormat(itype = 1)
    # itype must be one of 'y' (year), 'q' (quarter in year), 'm' (month in year), 'd' (day in month in year), 'w' (week in year), 'D' (weekday in month in year), 'qo' (quarter only), 'mo' (month only), 'do' (day only), 'dm' (day in month), 'wo' (week only), 'Do' (weekday only), 'Dy' (weekday in year)
  )

})

