#
# This test file has been generated by kwb.test::create_test_files()
#

test_that("hsTsAfter() works", {

  expect_error(
    kwb.datetime:::hsTsAfter(tstamps = 1, tsLimit = 1)
    # datetime is not of one of the supported classes 'character', 'Date', 'POSIXt'
  )
   expect_error(
    kwb.datetime:::hsTsAfter(tstamps = "a", tsLimit = 1)
    # character string is not in a standard unambiguous format
  )
   expect_error(
    kwb.datetime:::hsTsAfter(tstamps = as.POSIXct("2018-06-03 23:50:00"), tsLimit = as.POSIXct("2018-06-03 23:50:00"))
    # replacement has length zero
  )

})

