#
# This test file has been generated by kwb.test::create_test_files()
#

test_that("utc_offset_Berlin_time() works", {

  expect_error(
    kwb.datetime:::utc_offset_Berlin_time(timestamps = NULL)
    # character string is not in a standard unambiguous format
  )
   expect_error(
    kwb.datetime:::utc_offset_Berlin_time(timestamps = 1)
    # all(hasTimeFormat(timestamps, "%Y-%m-%d %H:%M:%S")) is not TRUE
  )

})

