#
# This test file has been generated by kwb.test::create_test_files()
#

test_that("hasTimeFormat() works", {

  kwb.datetime:::hasTimeFormat(timestamps = NULL)
   kwb.datetime:::hasTimeFormat(timestamps = numeric())
   kwb.datetime:::hasTimeFormat(timestamps = 1)
   kwb.datetime:::hasTimeFormat(timestamps = 1:2)
   kwb.datetime:::hasTimeFormat(timestamps = character())
   kwb.datetime:::hasTimeFormat(timestamps = 'a')
   kwb.datetime:::hasTimeFormat(timestamps = c('a', 'b'))
   kwb.datetime:::hasTimeFormat(timestamps = logical())
   kwb.datetime:::hasTimeFormat(timestamps = TRUE)
   kwb.datetime:::hasTimeFormat(timestamps = FALSE)

})

