#
# This test file has been generated by kwb.test::create_test_files()
#

test_that("getTimestepInSeconds() works", {

  expect_error(
    kwb.datetime:::getTimestepInSeconds(timestamps = NULL)
    # "POSIXt" %in% class(timestamps) is not TRUE
  )

})

