#
# This test file has been generated by kwb.test::create_test_files()
#

test_that("sequenceOfTimestamps() works", {

  expect_error(
    kwb.datetime:::sequenceOfTimestamps(from = NULL, to = NULL)
    # is.character(from) && is.character(to) is not TRUE
  )
   expect_error(
    kwb.datetime:::sequenceOfTimestamps(from = character(), to = character())
    # 'from' must be of length 1
  )
   expect_error(
    kwb.datetime:::sequenceOfTimestamps(from = 'a', to = character())
    # character string is not in a standard unambiguous format
  )

})

