#
# This test file has been generated by kwb.test::create_test_files()
#

test_that("daylightSavingTimeInEffect() works", {

  expect_error(
    kwb.datetime:::daylightSavingTimeInEffect(x = NULL)
    # "POSIXt" %in% class(x) is not TRUE
  )

})

