#
# This test file has been generated by kwb.test::create_test_files()
#

test_that("utcOffset() works", {

  kwb.datetime:::utcOffset(LocalDateTime = character(), DateTimeUTC = character())
   expect_error(
    kwb.datetime:::utcOffset(LocalDateTime = NULL, DateTimeUTC = NULL)
    # is.character(LocalDateTime) && is.character(DateTimeUTC) is not TRUE
  )
   expect_error(
    kwb.datetime:::utcOffset(LocalDateTime = character(), DateTimeUTC = 'a')
    # character string is not in a standard unambiguous format
  )

})

