#
# This test file has been generated by kwb.test::create_test_files()
#

test_that("reformatTimestamp() works", {

  kwb.datetime:::reformatTimestamp(x = character())
   kwb.datetime:::reformatTimestamp(x = 'a')
   kwb.datetime:::reformatTimestamp(x = c('a', 'b'))
   expect_error(
    kwb.datetime:::reformatTimestamp(x = NULL)
    # is.character(x) is not TRUE
  )

})

