#
# This test file has been generated by kwb.test::create_test_files()
#

test_that("timestampIn() works", {

  kwb.datetime:::timestampIn(tstamps = NULL)
   kwb.datetime:::timestampIn(tstamps = numeric())
   kwb.datetime:::timestampIn(tstamps = 1)
   kwb.datetime:::timestampIn(tstamps = 1:2)
   kwb.datetime:::timestampIn(tstamps = character())
   kwb.datetime:::timestampIn(tstamps = 'a')
   kwb.datetime:::timestampIn(tstamps = c('a', 'b'))
   kwb.datetime:::timestampIn(tstamps = logical())
   kwb.datetime:::timestampIn(tstamps = TRUE)
   kwb.datetime:::timestampIn(tstamps = FALSE)

})

