#
# This test file has been generated by kwb.test::create_test_files()
#

test_that("utc_offset_Berlin_day() works", {

  expect_error(
    kwb.datetime:::utc_offset_Berlin_day(x = 1)
    # is.character(x) is not TRUE
  )
   expect_error(
    kwb.datetime:::utc_offset_Berlin_day(x = "a")
    # all(hasTimeFormat(x, "%Y-%m-%d")) is not TRUE
  )

})

