#
# This test file has been generated by kwb.test::create_test_files()
#

test_that("hsQua() works", {

  kwb.datetime:::hsQua(month = NULL)
   kwb.datetime:::hsQua(month = numeric())
   kwb.datetime:::hsQua(month = 1)
   kwb.datetime:::hsQua(month = 1:2)
   kwb.datetime:::hsQua(month = logical())
   kwb.datetime:::hsQua(month = TRUE)
   kwb.datetime:::hsQua(month = FALSE)
   expect_error(
    kwb.datetime:::hsQua(month = character())
    # non-numeric argument to binary operator
  )

})

