#
# This test file has been generated by kwb.test::create_test_files()
#

test_that("resetTimePart() works", {

  expect_error(
    kwb.datetime:::resetTimePart(tstamp = NULL, resetHour = NULL)
    # character string is not in a standard unambiguous format
  )
   expect_error(
    kwb.datetime:::resetTimePart(tstamp = numeric(), resetHour = NULL)
    # invalid 'trim' argument
  )

})

