#
# This test file has been generated by kwb.test::create_test_files()
#

test_that("daylightSavingTimeInEffect() works", {

  kwb.datetime:::daylightSavingTimeInEffect(x = as.POSIXct("2018-06-03 23:50:00"))
   expect_error(
    kwb.datetime:::daylightSavingTimeInEffect(x = 1)
    # "POSIXt" %in% class(x) is not TRUE
  )

})

