#
# This test file has been generated by kwb.test::createTestFiles()
#

test_that("roundTime() works", {

  expect_error(roundTime())
})

test_that("minTimeStep() works", {

  expect_error(minTimeStep())
})

test_that("getTimestepInSeconds() works", {

  expect_error(getTimestepInSeconds())
})

test_that("isValidTimestampSequence() works", {

  expect_error(isValidTimestampSequence())
})

test_that("sequenceOfTimestamps() works", {

  expect_error(sequenceOfTimestamps())
})

