#
# This test file has been generated by kwb.test::create_test_files()
#

test_that("to.GMT.plus.1() works", {

  kwb.datetime:::to.GMT.plus.1(timestamp = character())
   kwb.datetime:::to.GMT.plus.1(timestamp = 'a')
   kwb.datetime:::to.GMT.plus.1(timestamp = c('a', 'b'))
   expect_error(
    kwb.datetime:::to.GMT.plus.1(timestamp = NULL)
    # is.character(timestamp) is not TRUE
  )

})

