#
# This test file has been generated by kwb.test::create_test_files()
#

test_that("hsTsInfo() works", {

  kwb.datetime:::hsTsInfo(tstamp = character())
   kwb.datetime:::hsTsInfo(tstamp = logical())
   expect_error(
    kwb.datetime:::hsTsInfo(tstamp = NULL)
    # do not know how to convert 'tstamp' to class “POSIXct”
  )
   expect_error(
    kwb.datetime:::hsTsInfo(tstamp = numeric())
    # 'origin' must be supplied
  )
   expect_error(
    kwb.datetime:::hsTsInfo(tstamp = 'a')
    # character string is not in a standard unambiguous format
  )

})

