#
# This test file has been generated by kwb.test::createTestFiles()
#

test_that("iso_to_localtime() works", {

  expect_error(iso_to_localtime())
})

test_that("decade() works", {

  expect_error(kwb.datetime:::decade())
})

test_that("to.GMT.plus.1() works", {

  expect_error(to.GMT.plus.1())
})

test_that("toGmtRelativePosix() works", {

  expect_error(toGmtRelativePosix())
})

test_that("stringToPosix() works", {

  expect_error(stringToPosix())
})

test_that("hsToPosix() works", {

  expect_error(hsToPosix())
})

test_that(".test_hsToPosix() works", {

  kwb.datetime:::.test_hsToPosix()
})

test_that("berlinNormalTimeToUTC() works", {

  expect_error(kwb.datetime:::berlinNormalTimeToUTC())
})

test_that("berlinNormalTimeToBerlinLocalTime() works", {

  expect_error(kwb.datetime:::berlinNormalTimeToBerlinLocalTime())
})

test_that("utcToBerlinLocalTime() works", {

  expect_error(kwb.datetime:::utcToBerlinLocalTime())
})

test_that("localNormalTimeToLocalTime() works", {

  expect_error(kwb.datetime:::localNormalTimeToLocalTime())
})

test_that("localNormalTimeToUTC() works", {

  expect_error(kwb.datetime:::localNormalTimeToUTC())
})

test_that("utcToLocalTime() works", {

  expect_error(kwb.datetime:::utcToLocalTime())
})

test_that("utcOffset() works", {

  expect_error(kwb.datetime:::utcOffset())
})

test_that("toUTC() works", {

  expect_error(toUTC())
})

test_that("toTimezone() works", {

  expect_error(kwb.datetime:::toTimezone())
})

