#
# This test file has been generated by kwb.test::create_test_files()
#

test_that("date_range_CEST() works", {

  expect_error(
    kwb.datetime:::date_range_CEST(year = NULL)
    # is.numeric(year) is not TRUE
  )
   expect_error(
    kwb.datetime:::date_range_CEST(year = numeric())
    # character string is not in a standard unambiguous format
  )
   expect_error(
    kwb.datetime:::date_range_CEST(year = 1)
    # all(year >= 1980) is not TRUE
  )

})

