#
# This test file has been generated by kwb.test::create_test_files()
#

test_that("matchingTimeFormat() works", {

  kwb.datetime:::matchingTimeFormat(timestamp = 'a', timeFormats = 1)
   kwb.datetime:::matchingTimeFormat(timestamp = 'a', timeFormats = 1:2)
   kwb.datetime:::matchingTimeFormat(timestamp = 'a', timeFormats = 'a')
   kwb.datetime:::matchingTimeFormat(timestamp = 'a', timeFormats = c('a', 'b'))
   kwb.datetime:::matchingTimeFormat(timestamp = 'a', timeFormats = TRUE)
   kwb.datetime:::matchingTimeFormat(timestamp = 'a', timeFormats = FALSE)
   expect_error(
    kwb.datetime:::matchingTimeFormat(timestamp = NULL, timeFormats = NULL)
    # Exactly one character timestamp expected!
  )
   expect_error(
    kwb.datetime:::matchingTimeFormat(timestamp = 'a', timeFormats = NULL)
    # argument to 'which' is not logical
  )

})

