#
# This test file has been generated by kwb.test::create_test_files()
#

test_that("hsDateStr() works", {

  kwb.datetime:::hsDateStr(tstamp = NULL)
   expect_error(
    kwb.datetime:::hsDateStr(tstamp = numeric())
    # invalid 'trim' argument
  )

})

