#
# This test file has been generated by kwb.test::create_test_files()
#

test_that("decade() works", {

  kwb.datetime:::decade(year = 1)
   kwb.datetime:::decade(year = 1:2)
   expect_error(
    kwb.datetime:::decade(year = "a")
    # is.numeric(year) is not TRUE
  )

})

