#
# This test file has been generated by kwb.test::create_test_files()
#

test_that("berlinNormalTimeToBerlinLocalTime() works", {

  kwb.datetime:::berlinNormalTimeToBerlinLocalTime(x = character())
   expect_error(
    kwb.datetime:::berlinNormalTimeToBerlinLocalTime(x = NULL)
    # is.character(x) is not TRUE
  )
   expect_error(
    kwb.datetime:::berlinNormalTimeToBerlinLocalTime(x = 'a')
    # character string is not in a standard unambiguous format
  )

})

