#
# This test file has been generated by kwb.test::create_test_files()
#

test_that("utcToLocalTime() works", {

  kwb.datetime:::utcToLocalTime(x = character(), tz = NULL)
   kwb.datetime:::utcToLocalTime(x = character(), tz = 'a')
   expect_error(
    kwb.datetime:::utcToLocalTime(x = NULL, tz = NULL)
    # is.character(x) is not TRUE
  )
   expect_error(
    kwb.datetime:::utcToLocalTime(x = character(), tz = numeric())
    # invalid 'tz' value
  )
   expect_error(
    kwb.datetime:::utcToLocalTime(x = 'a', tz = NULL)
    # character string is not in a standard unambiguous format
  )

})

